### ISSUE TITLE
HashMap.put() API mismatch with Zig 0.16.0-dev.3133 - build.zig fails with "expected 2 arguments, found 3"

### ISSUE THREAD

**Issue by 4bdullah0** [raylib-zig/raylib-zig#327]
## Issue
The devel branch of raylib-zig fails to build with Zig 0.16.0-dev.3133+5ec8e45f3
The build.zig uses the old HashMap.put() API that requires an allocator argument, 
but recent Zig versions changed the API to only take 2 arguments (key, value)

---

## Error

zig-pkg\raylib-6.0.0-...\build.zig:504:18: error: member function expected 2 argument(s), found 3
b.modules.put(b.graph.arena, "raygui", c_mod) catch @panic("OOM");

---

Note: This appears to be a breaking change in Zig's HashMap API. 
The old API `put(allocator, key, value)` changed to `put(key, value)` 
in Zig 0.16.0-dev versions.

---

## Steps to Reproduce
1. Use Zig version 0.16.0-dev.3133 or later
2. Fetch raylib-zig devel branch: `zig fetch --save git+https://github.com/raylib-zig/raylib-zig#devel`
3. Run: `zig build run`

## Expected Behavior
Build should succeed with latest Zig dev versions

## Current Behavior
Build fails with HashMap.put() API mismatch errors on lines 504 and 603 in build.zig

## Workaround
Downgrading to a previous raylib-zig version works fine

## Environment
- Zig version: 0.16.0-dev.3133+5ec8e45f3
- OS: Windows
- raylib-zig branch: devel (commit 47766db82f30aece1d72c935edc71bc33d268fd6)

**Comment by Not-Nik** [comment]
You should use the 0.16.0 release
